name: AzLink
version: ${pluginVersion}
author: Azuriom Team
description: The plugin to link your Azuriom website with your server.
website: https://azuriom.com
main: com.azuriom.azlink.bukkit.AzLinkBukkitPlugin
api-version: 1.13
softdepend: [nLogin, PlaceholderAPI, SkinsRestorer]
loadbefore: [AuthMe]
folia-supported: true
commands:
  azlink:
    description: Manage the AzLink plugin.
    usage: /<command> [status|setup|fetch|port]
    aliases: [azuriomlink]

permissions:
  azlink.admin:
    description: Allows you to use the /azlink command.
    default: op