repositories {
    maven { url = 'https://maven.hytale.com/release/' }
}

def hytaleVersion = '0.5.3'

dependencies {
    implementation project(':azlink-common')
    compileOnly "com.hypixel.hytale:Server:${hytaleVersion}"
}

processResources {
    filesMatching('**/*.json') {
        expand('pluginVersion': version, 'hytaleVersion': hytaleVersion ?: '*')
    }
}
