name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean shadowJar
    - uses: actions/upload-artifact@master
      with:
        name: AzLink
        path: universal/build/libs/AzLink.jar
    - uses: actions/upload-artifact@master
      with:
        name: AzLink-Legacy
        path: universal-legacy/build/libs/AzLink-Legacy.jar
